name: Build Documentation
on:
  workflow_dispatch:
  push:
    paths:
      - 'build/coverage.xml'
jobs:
  docs:
    name: Build docs with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: latest
            products: Signal_Processing_Toolbox Parallel_Computing_Toolbox
      - name: Delete tests
        run: rm -r test/ 
      - name: Reformat 1-liners
        uses: matlab-actions/run-command@v2
        with:
          command: addpath build; reformat1liners();  
      - name: Build documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install sphinxcontrib-matlabdomain"
          build-command: "make html"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

        
          