name: Build Documentation
on:
  workflow_dispatch:
  push:
    branches: ['dev-docs']
jobs:
  docs:
    name: Build docs with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Delete tests and FMM duplicates
        run: rm -r test/ src/FMM/
      - name: Install sphinx
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          git clone https://github.com/sphinx-contrib/matlabdomain.git ../matlabdomain
          pip install -e ../matlabdomain
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: latest
            products: Signal_Processing_Toolbox Parallel_Computing_Toolbox
      - name: Reformat 1-liners
        uses: matlab-actions/run-command@v2
        with:
          command: addpath build; reformat1liners();  
      - name:  Build documentation
        run: |
          source .venv/bin/activate
          cd docs/
          sphinx-build -M html source/ build/
          cd ../
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

        
          