name: Build Documentation
on:
  workflow_dispatch:
  push:
    branches: ['dev-docs']
jobs:
  docs:
    name: Build docs with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: latest
            products: Signal_Processing_Toolbox Parallel_Computing_Toolbox
      - name: Delete tests
        run: rm -r test/ 
      - name: Reformat 1-liners
        uses: matlab-actions/run-command@v2
        with:
          command: addpath build; reformat1liners();  
      - name: Install sphinx and build documentation
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install sphinxcontrib-matlabdomain
          cd docs/
          make html
          cd ../
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

        
          